name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC every day

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get Dependencies
      run: sudo apt update && sudo apt -y install libx11-dev libpng-dev ffmpeg imagemagick

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Checkout the other repository
      uses: actions/checkout@v2
      with:
        repository: 'ignacionr/2dstory'
        ref: 'main'
        ssh-key: ${{ steps.setup-ssh.outputs.ssh-private-key }}
        path: '2dstory'
   
    - name: Build
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      run: cd 2dstory && ./build.sh

    - name: Generate Video
      run: cd 2dstory && ./release.sh

    - name: remove build stuff
      run: rm -Rf ${{github.workspace}}/2dstory

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '/tmp/public'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
